= JavaScript lernen
:toc: left
:toclevels: 3
:tip-caption: 💡
:warning-caption: ⚠️
:source-highlighter: rouge
:docinfo: shared-head

== Einleitung

In diesem Tutorial wirst du Programmieren lernen.
Du lernst wie man mit der Programmiersprache JavaScript 2D-Grafiken zeichnet,
Elemente animiert und auf Benutzereingaben reagiert.

Am Ende des Tutorials kennst du die grundlegenden Bausteine moderner Programmiersprachen und kannst diese verwenden,
um eigenständig deine Ideen als Computer-Programm zu realisieren.

=== Aufbau

Das Tutorial ist in Kapitel unterteilt. In jedem Kapitel lernst du neue Bausteine kennen.
Mit jedem Baustein kannst du komplexere / vielfältigere Programme schreiben.
Pro Kapitel gibt es verschiedene Theorie- und Übungsblöcke.

Die Inhalte beschränken sich auf das Kursziel. Weiteführende, empfehlenswerte Lernquellen sind am Ende aufgeführt.

=== Tools / Werkzeuge
Um unseren Programmcode (kurz Code) zu schreiben verwenden wir einen Texteditor.
Einen speziellen Texteditor, welcher extra gemacht ist um Programme zu schreiben; eine sogenannte *IDE* (Integrated Development Environment).
Eine IDE ist für Programmierer, wie Word für Berichteschreiber. Eine IDE versteht eine Programmiersprache, sie bietet Hilfestellung bei Schreibfehlern, formatiert den Text und rückt korrekt ein etc.
Es gibt viele verschiedene IDEs, wir verwenden das frei verfügbare Programm "Visual Studio Code" (kurz vscode).

In diesem Tutorial lernen wir zudem P5.js kennen. Damit können wir 2D-Grafiken zeichnen. P5.js bietet einen einfachen Texteditor (eine leichtgewichtige IDE) an, welcher direkt im *Browser* läuft.

Um unseren Code auszuführen, also zum Beispiel um die Grafiken zu rendern, verwenden wir einen *Browser* (Chrome, Firefox, Safari oder Edge).

== Anweisungen & Variablen

=== Anweisungen
Ein Computerprogramm (kurz Programm) besteht aus einer Sequenz von Anweisungen. Jede Anweisung (engl. statement) veranlasst den Computer dazu etwas zu tun.
Mögliche Dinge die man tun kann:

* Mathematische Berechnung
* Eine Datei einlesen
* Eine Linie zeichnen
* Rückfrage an den Benutzer (z.B. "Sind sie sicher, dass sie diese Datei löschen wollen?")

Im folgenden JavaScript Programmcode ist jede Zeile eine Anweisung.

[source,javascript,linenums]
----
1 + 3
Math.sqrt(25)
"Hallo " + prompt("Wie ist dein Name?")
----

Die Anweisungen werden sequentiell von oben nach unten ausgeführt.

Die erste Zeile weist den Compter an, zwei Zahlen zu addieren, das Ergebnis ist 4.

Die zweite Zeile berechnet die Quadratwurzel (engl. Square Root, sqrt) aus 25, das Ergebnis ist 5.

Die dritte Zeile fragt den User (engl. für Benutzer) nach dem Namen. Hat der User den Namen eingegeben, wird diese Eingabe verwendet und an die Zeichenkette "Hallo " angehängt. Das Ergebnis ist "Hallo <NAME>".

==== Übung - Anweisungen
****
1. Öffne einen Browser
1. Öffne die https://balsamiq.com/support/faqs/browserconsole/[Entwicklertools]
1. Öffne die console in den Entwicklertools
1. Führe eine Zeile nach der anderen (der drei Beispiele oben) in der
console aus. Dazu einfach die Zeile eingeben und dann mit der Enter-Taste ausführen.
****

=== Kommentare
Eine spezielle Anweisung ist ein Kommentar. Ein Kommentar ist ein Stück Code, welches vom Computer nicht ausgeführt wird. Kommentare sind dazu da, den restlichen Code zu beschreiben. Sie sind also für den Code-Leser gedacht, für Programmierer selbst.

[source,javascript,linenums]
----
// Addiere 1 und 3
1 + 3
/*
Mehrzeiliger Kommentar ...
...
Ende Kommentar
*/
Math.sqrt(25) // Quadratwurzel von 25
Math./*Kommentar innerhalb einer Anweisung, einfach weils geht :)*/sqrt(25)
----

TIP: Kommentare sind zu Beginn hilfreich. Später, wenn du die Grundlagen des Programmierens kennst, solltest du Kommentare aber sehr sparsam einsetzen. Als Programmierer ist es nämlich unsere Aufgabe den Code so zu schreiben, dass erläuternde Kommentare kaum notwendig sind.


=== Variablen
Mit einer Variable können Werte gespeichert werden. Das ist sehr praktisch. Denn jede Variable hat einen Namen. So kann man später im Programm via Namen auf den gespeicherten Wert zugreifen.

Das Beispiel der Addition von oben, nun mit Variablen:

[source,javascript,linenums]
----
a = 1
b = 3
summe = a + b
----

Jede Zeile im obigen Beispiel ist eine Anweisung.
Bei allen drei Anweisungen handelt es sich um Variable-Definitionen. Das heisst es wird eine Variable erstellt und der Variable wird mithilfe des Gleicheitszeichens (=) direkt ein Wert zugewiesen (engl. Assignment).

Nachdem die erste Zeile ausgeführt ist, hat die Variable `a` den Wert 1.

Nachdem die zweite Zeile ausgeführt ist, hat die Variable `b` den Wert 3.

Nachdem die dritte Zeile ausgeführt ist, hat die Variable `summe` den Wert 4.

Auf Zeile 3 wird auf die Variablen `a` und `b` zugegriffen und deren Werte werden ausgelesen und für die Addition verwendet.
Man sagt auch, Zeile 3 referenziert die Variablen `a` und `b`.


Weil der Computer die Anweisungen von oben nach unten ausführt, ist es also nicht möglich, Zeile 3 nach oben zu verschieben. Denn dann würde man versuchen auf eine Variable zuzugreifen die es noch gar nicht gibt.

[source,javascript,linenums]
----
a = 1
summe = a + b // Error. Variable b ist nicht definiert
b = 3
----

Allerdings ist es möglich die Zeilen 1 und 2 zu tauschen.

[source,javascript,linenums]
----
b = 3
a = 1
summe = a + b
----

==== Variablenamen / Bezeichner
In JavaScript kann eine Variable einen langen, sprechenden Namen haben. Das ist sehr praktisch. Denn dadurch ist klar, welcher Wert in der Variable gespeichert ist.

Im Folgenden eine Liste von gültigen Namen: `a, name, backgroundColor, first_name`. +
Einige Zeichen sind nicht erlaubt, z.B. Umlaute und die meisten Sonderzeichen. In der Praxis sind die einzigen zwei Sonderzeichen, die man hin und wieder sieht `_, $`.

TIP: Der Name ist frei wählbar und sollte dem Inhalt / Zweck des Wertes der Variable entsprechen. Das macht es deutlich einfacher den Code zu verstehen, wenn man ihn als Mensch liest. Für den Computer selbst hat der Name keinerlei Bedeutung.


==== Variablearten
Die Variable-Definitionen im obigen Beispiel sind kurz und sprechend, es fehlt jedoch ein sehr wichtiges Detail.
In JavaScript gibt es zwei unterschiedliche Variablearten: *veränderbare* und *unveränderbare*, sogenannte Konstanten.

Veränderbaren Variablen kann mehrfach ein Wert zugewiesen werden. Konstanten kann nur einmal ein Wert zugewiesen werden.
Veränderbare Variablen erkennt man an dem <<keyword>> `let`, unveränderbare am Keyword `const`.

[source,javascript,linenums]
----
const a = 1
a = 11    // Error, a ist bereits definiert
let b = 3 // Definition der Variable b
b = 33    // der bestehenden Variable b einen neuen Wert zuweisen
let summe = a + b // summe = 11 + 33 = 44
b = 42
const zweiteSumme = a + b // zweiteSumme = 42 + 11 = 53
// summe = 44
----

Der obige Code läuft nur dann fehlerfrei komplett durch, wenn Zeile 2 gelöscht wird.

Nachdem eine Variable mit `let` definiert wurde, kann ihr zu einem beliebigen späteren Zeitpunkt ein neuer Wert zugewiesen werden; oben auf Zeile 4 und 6.
Die Berechnung auf Zeile 5 wird nur einmal gemacht, das heisst die Zuweisung auf Zeile 6, hat keinen Einfluss auf den Wert der Variable `summe`.

Eine Variabel kann nur einmal definiert werden (mit `let` oder `const`). Danach wird diese nur noch mit dem Namen angesprochen. Entweder für neue Wertzuweisungen, oder um den Wert auszulesen.

WARNING: Es ist wichtig, dass beim Anlegen einer Variable, immer `let` oder `const` verwendet wird.

TIP: Nachdem du in der console eine Variable definiert hast mit `let` oder `const`, kannst du deren Wert einfach abrufen, indem du lediglich den Variablenamen eingibst und Enter drückst.


=== Lernkontrolle
Ich weiss, ...
====
* [*] was eine Anweisung ist
* [*] wie ich eine Variable anlege
* [*] wie ich einer Variable einen Wert zuweise
* [*] welche Variablearten es gibt
====


== 2D Zeichnen
Du bist nun bereit ein neues Kapitel aufzuschlagen: Das Zeichnen und Animieren von zweidimensionalen geometrischen Formen.

Um einen Computer anzuzweisen eine Linie zu zeichnen, müssen wir ganz genau sagen wie diese Linie auszusehen hat. Also die Position, Länge, Farbe und Breite der Linie. Die Art und Weise wie wir Position und Länge definieren wird im Folgenden erläutert. Um die Farbe und Breite kümmern wir uns später.

=== Zeichenfläche
Die Zeichenfläche, auf der die Linie entstehen soll, ist ein Rechteck. Dieses Rechteck ist in ein Raster unterteilt (unten im Bild rechts). Ähnlich wie bei einem Blatt Papier mit einem vorgezeichneten Gittermuster. {nbsp} +
Aus dem Mathematikunterricht kennst du etwas ähnliches, das kartesische Koordinatensystem (unten im Bild links). Im Unterschied zum kartesischen System, ist beim Koordinatensystem unserer Zeichenfläche der 0-Punkt ganz oben Links. Es gibt also nur einen Quadranten, und alle Punkte im Koordinatensystem haben positive x- und y-Werte.

image::media/drawing-2d.svg[system,300,300,align=center]

Möchten wir also eine diagonale Linie zeichnen, von oben Links nach unten Rechts, müssen wir eine Möglichkeit finden, dem Computer zu befehlen: {nbsp} +
"Zeichne eine Linie von Punkt (0, 0) bis Punkt (6, 6)".

Um solche Anweisungen geben zu können, müssen wir zuerst ein neues Programmelement kennen lernen: Funktionen.


== Funktionen – Aufrufen
Eine Funktion ist quasi ein eigenständiges Mini-Programm, welches über dessen Namen gestartet werden kann. Über eine Liste von Werten (`Parameter`), können wir dem Mini-Programm genau sagen, was es für uns tun soll.

In JavaScript existieren bereits viele vorgefertigte Funktionen, diese können wir als Programmierer direkt verwenden.

Um eine Linie zu zeichnen können wir zum Beispiel folgenden Code verwenden:

[source,javascript,linenums]
----
const startX = 0
const startY = 0
const endX = 6
const endY = 6
line(startX, startY, endX, endY)
----

Zeile 1-4:
Der Startpunkt ist ganz oben links, dieser hat die Koordinaten (x=0, y=0), kurz (0, 0). Der Endpunkt ist ganz unten rechts, dieser hat die Koordinaten (6, 6).

Auf Zeile 5 wird die Funktion namens `line` aufgerufen. Die Komma-separierten Werte in den Klammern nennt man `Parameter`. Sie beschreiben, was die Funktion konkret tun soll. In diesem Fall beschreiben die ersten beiden Werte die Koordinaten der Startpunks, und die letzten beiden Werte die Koordinaten des Endpunkts.

Es gibt viele weitere nützliche Funktionen. Du hast z.B. ganz zu Beginn die Funktion `Math.sqrt` kennen gelernt. Diese hat nur einen Parameter. Nämlich die Zahl von der man gerne die Quadratwurzel berechnet haben möchte. Die Funktion `line` hat 4 Parameter. Es gibt auch Funktionen ohne Parameter, und sogar welche, bei der die Anzahl der Parameter variabel ist.



=== Übung – Funktionen aufrufen
Ein kleines Beispiel mit der Funktion `prompt`, welche du ebenfalls bereits kennengelernt hast zu Beginn.

****
*Prompt*

Was ist der Unterschied der folgenden beiden Zeilen? Wie wirkt sich dieser Unterschied aus, wenn du die beiden Zeilen ausführst?

[source,javascript,linenums]
----
prompt()
prompt("Wie heisst du?")
----


.Lösung (Click)
[%collapsible]
====
Zeile 1 ruft die Funktion prompt auf, ohne Parameter. Als Ergebnis wird ein Eingabe-Dialog angezeigt ohne textuelle Aufforderung, sondern lediglich mit einem Eingabefeld. {nbsp} +
Zeile 2 zeigt einen Eingabe-Dialog mit textueller Aufforderung.
====

****


Das tolle an Funktionen ist, dass man sie beliebig oft nacheinander aufrufen kann. Möchte man also von drei verschiedenen Zahlen die Quadratwurzel ziehen kann man die Funktion einfach dreimal aufrufen, jedesmal mit einem anderen Parameter:

[source,javascript,linenums]
----
Math.sqrt(25)
Math.sqrt(36)
Math.sqrt(2)
// Ich kann sogar die Wurzel einer Wurzel berechnen:
let nine = Math.sqrt(81)
let three = Math.sqrt(nine)
// Oder noch kürzer:
three = Math.sqrt(Math.sqrt(81))
----

'''

Als nächstes lernen wir ein Werkzeug kennen, welches die Funktion `line` ausführen kann und eine Linie auf den Bildschirm zeichnet. Denn wenn du den Code von oben kopierst und direkt im Browser ausführst, wird das einen Fehler geben. Der Grund ist, dass es die Funktion `line` nicht gibt. Zudem gäbe es auch noch keine Zeichenfläche ;).

=== Lernkontrolle
Ich weiss, ...
====
* [*] was eine Funktion ist
* [*] was ein Parameter ist
* [*] wie ich eine Funktion aufrufe
====

== P5.js – Einführung
Im Folgenden siehst du ein einfaches Programm, welches mithilfe von P5.js eine Linie zeichnet. Klicke auf "Play" um das Programm auszuführen und das Ergebnis zu sehen.

++++
<script type="text/p5" data-height="300">
createCanvas(200, 200)
background('skyblue')
line(0, 0, 200, 200)
</script>
++++
{nbsp} +

Cool! Aber was geschieht da genau?

1. Die Funktion `createCanvas` erstellt eine Zeichenfläche. Diese ist 200 Einheiten (sogenannte <<Pixel>>) breit und 200 Einheiten hoch.
1. Mit `background` setzen wir die Hintergrundfarbe der Zeichenfläche. `skyblue` ist eine Farbbezeichnung die der Computer kennt.
1. Mit `line` zeichnen wir dann die diagonale Linie, von oben links nach unten rechts.

=== Übung – 2D Zeichnen
Du kannst diese Übungen direkt im obigen Editor lösen.

Wichtige Resourcen:

* Formen zeichnen: https://processing.org/tutorials/drawing
* Vollständige Dokumentation aller Funktionen von P5.js: https://p5js.org/reference

****
*Linie*

Zeichne eine zweite Linie von unten links nach oben rechts.

*Farben*

1. Verändere die Hintergrundfarbe. Auswahl an Farbnamen https://www.w3schools.com/colors/colors_names.asp
1. Verändere die Linienfarbe. Zeichne Linien in verschiedenen Farben. +
Hinweis: Die `stroke` Funktion

*Farben & Formen*

Zeichne:

+++
<iframe src="p5-sketches/index.html?s=pendel" style="border:0; height: 200px;"></iframe>
+++

*Symbol*

Zeichne selbst etwas bestimmtes. z.B. ein Haus oder ein Ying-Yang Symbol oder was dir gerade in den Sinn kommt :).

Inspiration:

+++
<iframe src="p5-sketches/index.html?s=peace" style="border:0; height: 200px;"></iframe>
+++
https://www.wihel.de/wie-das-peace-symbol-entstanden-ist/

****

=== Lernkontrolle
Ich weiss, ...
====
* [*] wie ich eine Linie, ein Kreis und ein Rechteck zeichne
* [*] wie ich die Farben und Linienstärke von Formen verändere
====

Du hast nun einiges gelernt und kannst 2D zeichnen mit P5.js. Das nächste Ziel ist das Erstellen von interaktiven Programmen, welche anhand von Benutzereingaben ihr Verhalten verändern, und so zum Beispiel auf einen Mausklick reagieren. Bevor wir das tun können, musst du dir aber noch ein wenig Theorie aneignen.

== Datentypen I

In einem Programm werden Daten verarbeitet. Diese Daten können unterschiedlicher Art sein. Es können zum Beispiel Zahlen sein. Oder eine Liste von Namen. Als Programmierer ist es wichtig, dass man genau weiss, für was man die Daten braucht, denn daraus leitet sich ab, welchen Datentyp man verwendet.

Mit Zahlen kann ich andere Dinge anstellen als mit einer Liste von Namen.
Es macht z.B. keinen Sinn zwei Namen zu einer Summe zu addieren. Sehr wohl kann es aber Sinn machen, zwei Zahlen zu einer Summe zu addieren.

In JavaScript hat jede Variable einen Datentyp. Genauer: Der Wert, welcher einer Variable zugewiesen wird hat einen Datentyp, die Variable übernimmt diesen Datentyp automatisch bei der Zuweisung.

Zwei wichtige Datentypen werden hier vorgestellt. Später lernen wir noch einige mehr kennen.

=== Zahlen (Number)
Damit können Ganzzahlen (sogenannte `Integer`) oder Fliesskommazahlen (sogenannte `Floats`) abgebildet werden. In JavaScript gibt es den Datentypen `Number`, welcher sowohl Floats als auch Integer beinhaltet.

[source,javascript,linenums]
----
const r = 14
const pi = 3.14
const area = pi * r**2
// area = 3.14 * 14 * 14 = 615.44
----

=== Zeichenketten (String)
Wird verwendet um eine beliebige Anzahl von Zeichen zu speichern. z.B. einen Personennamen, eine Automarke oder ein Gedicht.

[source,javascript,linenums]
----
const greeting = "Hallo!"
const brand = "Mercedes Benz"
----

Mit dem `+` Zeichen ist es möglich zwei Strings miteinander zu verbinden, und damit einen neuen String zu erzeugen.

[source,javascript,linenums]
----
const greeting = "Hallo"
const name = " Mrs. Simpson"
const text = greeting + name
// text ist jetzt "Hallo Mrs. Simpson"
// greeting und name bleiben unverändert
----


TIP: Mit dem Keyword `typeof` kannst du den Datentypen eines Wertes abfragen. z.B. `typeof "23"` ergibt `"string"`, `typeof 23` ergibt `"number"`.

==== Typen kombinieren

Eine Zahl kann ebenfalls in einer Zeichenkette gespeichert werden.
Dann kann man damit aber nicht mehr rechnen.

Folgendes ist also keine gültige Addition:

[source,javascript,linenums]
----
const summe = "3.14" + 5
----

Hingegen kann eine Zahl immer automatisch zu einem String umgewandelt werden. Folgendes ist also sinnvoll:

[source,javascript,linenums]
----
const temp = 35.8
const text = "Temperatur: " + temp
----


=== Boolean & Vergleiche
Ein Algorithmus muss oft Entscheidungen treffen. So muss ein Sortieralgorithmus zum Beispiel zwei Zahlen vergleichen und entscheiden welches der beiden Zahlen zuerst kommen soll.
Im folgenden Beispiel entscheidet ein Algorithmus, ob noch genug Geld auf dem Konto verfügbar ist, um einen Einkauf zu tätigen.

[source,javascript,linenums]
----
const accountBalance = 3000 // Kontostand
const articlePrice = 2850
// ist genug Geld auf dem Konto um Artikel zu kaufen?
const canBuy = acccountBalance > articlePrice
// canBuy = true
----

Auf Zeile vier werden zwei Werte verglichen. Das Ergebnis ist entweder "ja" oder "nein". Ein Datentyp, welcher nur diese beiden Werte kennt, nennt man `Boolean`. In JavaScript entspricht "ja" dem Wert `true` und "nein" dem Wert `false`.
Im obigen Beispiel hat also die Variable `canBuy` den Wert `true`.

Nebst > ist auch <, >= und \<= möglich.


==== Gleichheit prüfen
Um zu prüfen ob zwei Werte gleich sind, wird in JavaScript `===` verwendet.

Einige einfache Beispiele:

[source,javascript,linenums]
----
23 === 23 // true
const a = 2
const x = a === 2   // true
const y = a === "2" // false, weil ein String nie gleich einer Number ist
----

Im folgenden Beispiel wird direkt innerhalb des Vergleichs eine Operation (`%` – Modulo) ausgeführt, und dann das Ergebniss der Operation geprüft, ob diese den Wert 0 ergab.

[source,javascript,linenums]
----
const anyNumber = 23
const isEven = anyNumber % 2 === 0
// isEven = false
----

Im obigen Beispiel ist die Variable `isEven` nur dann true, wenn der Wert von `anyNumber` eine gerade (engl. even) Zahl ist. Der Modulo Operator (`%`) berechnet den Rest einer Division.


==== Logische Ausdrücke

Boolean Werte kann man auch miteinander verknüpfen. Zwei häufig verwendete Operationen sind `und` (engl. and) und `oder` (engl. or).
Es geht also darum logische Aussagen, die entweder wahr oder falsch sind, miteinander zu kombinieren. Das Ergebnis ist dann wiederum ein boolscher Wert.

Folgendes Beispiel illustriert die `or` Operation:

Ein Online-Shop gewährt 10% Rabatt, wenn die Kundin weniger als 20 Jahre alt ist, oder wenn die Kundin mehr als 300.- CHF im Warenkorb hat. Im Code könnte man das so abbilden:

[source,javascript,linenums]
----
const basketTotal = 344.65
const yearOfBirth = 1980
const youngerThan20 = (today('year') - yearOfBirth) < 20
const has10Discount = basketTotal > 300 || youngerThan20
----

Auf Zeile 4 werden zwei boolsche Werte mit `or` kombiniert. In JavaScript wird dafür der `||`-Operator verwendet. `has10Discount` ist also immer nur dann true, wenn mindestens ein Operand true ist. Der `or` Operator hat zwei Operanden, einer links und einer rechts vom `||` Zeichen.

__Quizfrage__ {nbsp} +
Welchen Variablenwert musst du ändern, damit `has10Discount` false wird?


Folgendes Beispiel illustriert die `and` Operation:

Gefragt sind alle Zahlen, welche gerade sind und durch vier teilbar:

[source,javascript,linenums]
----
const number = 23
const goodNumber = number % 2 === 0 && number % 4 === 0 
----

Auf Zeile 2 werden zwei boolsche Werte mit `and` kombiniert. In JavaScript wird dafür der `&&`-Operator verwendet.

Es können beliebig viele boolean Werte miteinander kombiniert werden. Möchte man _und_ und _oder_ miteinander mischen, ist zu empfehlen die Teilausdrücke in runde Klammern zu setzen, oder in eine Variable auszulagern:

[source,javascript,linenums]
----
const number = 23
const goodNumber = number % 2 === 0 && number % 4 === 0 
const goodPositive1 = goodNumber && number >= 0
const goodPositive2 = number % 2 === 0 && number % 4 === 0 && number >= 0
const goodOrNegative1 = goodNumber || number < 0
const goodOrNegative2 = (number % 2 === 0 && number % 4 === 0) || number < 0
const goodOrNegative3 = number % 2 === 0 && number % 4 === 0 || number < 0
----

Die Zeilen 3 und 4, sowie 5, 6 und 7 sind jeweils äquivalent. Auf Zeile 6 wird _und_ mit _oder_ gemischt, deshalb werden runde Klammern verwendet. Das erhöht die Lesbarkeit und verdeutlicht die Intension des Autors. {nbsp} +
 Auf Zeile 7 wird ebenfalls _und_ mit _oder_ gemischt, aber ohne runde Klammern. Trotzdem ist das Ergebnis stets korrekt. Das ist so, weil der _und_ Operator zuerst geprüft wird. So ähnliche wie die altbekannte Eselsbrücke beim Multiplizieren und Addieren: "Punkt vor Strich", heisst es hier: "Und vor Oder".

Zur Illustration kann das Ergebnis der Zeile 7 in mehreren Schritten hergeleitet werden:
 
[source,javascript,linenums]
----
const number = 23
const goodOrNegative = number % 2 === 0 && number % 4 === 0 || number < 0

// 1. Modulo auflösen
                     = 1 === 0 && 3 === 0 || number < 0

// 2. Operanden auflösen
                     = false && false || false

// 3. Operanden nach Priorität auflösen
                     = false || false

// 4. Operanden auflösen
                     = false
----


=== Lernkontrolle
Ich weiss, ...
====
* [*] dass ich nur Variablen mit gleichem Datentyp vergleichen kann
* [*] was ein logischer Ausdruck ist
* [*] den Unterschied von Integer und Float
* [*] wie ich Strings kombinieren kann
====


== P5.js - Animationen
Bevor wir mit P5.js bewegte Bilder zeichnen können, müssen wir P5.js noch etwas vertiefter kennen lernen.

Sämtliche P5.js Programme beinhalten Anweisungen, welche in zwei Gruppen aufgeteilt werden können: Einmal ausgeführte und wiederholt ausgeführte.

*Einmal ausgeführt*: Werden beim Programm start einmalig ausgeführt, dann nie wieder. {nbsp} +
*Wiederholt ausgeführt*: Werden automatisch alle par Millisekunden ausgeführt.

Bis jetzt hatten wir nur mit einmal ausgeführten Anweisungen zu tun. Du hast im Editor einmal auf den `Run`-Button gedrückt und die Zeichnung wurde erstellt. Die Aufgabe des Programms war damit erledigt.

Möchten wir jetzt aber, dass sich das Bild verändert (ohne das wir erneut Run drücken), brauchen wir eine Gruppe von Befehlen, welche automatisch wiederholt ausgeführt wird, und unter bestimmten Bedingungen unser Bild verändert.

Folgendes Beispiel zeigt eine Animation. Der Kreis pulsiert.

++++
<script type="text/p5" src="p5-sketches/animation-demo.js" data-height="400">
</script>
++++

{nbsp} +

Alle einmal ausgeführten Anweisungen kommen in die Funktion `setup` platziert.
Alle wiederholt ausgeführten in die Funktion `draw`. Die Funktion draw wird automatisch alle ca. 60 Millisekunden ausgeführt. Für uns Menschen sieht die Animation trotzdem flüssig aus, weil das menschliche Auge ein ruckeln / flimmern nur dann erkennt, wenn das Bild weniger als alle 25 Millisekunden aufgebaut werden würde.

Die Namen der Funktionen müssen genau so heissen, wie im Code oben. Denn nur dann "weiss" P5.js welche Anweisungen einmalig oder wiederholt ausgeführt werden müssen. Man spricht auch von einer `Namenskonvention`, welche vom `Framework` (P5.js), als Rahmenbedingung (engl. frame = Rahmen) vorgegeben wird.

TIP: Das ist das erste mal dass du siehst, wie man eine Funktion selbst erstellt. Vorerst lassen wir es dabei, es reicht wenn du innerhalb der Funktionen deine Anweisungen korrekt platzieren kannst. Mehr Details zu Funktionen folgen später.


=== Übung – 2D Animationen
Du kannst diese Übungen direkt im obigen Editor lösen.

****
*Ruckel*

Verwende im Beispiel oben die Funktion `frameRate`, um eine ruckelnde Animition zu erstellen.

*Floating Rect*

Zeichne ein Rechteck, welches sich automatisch von ganz Links nach ganz Rechts bewegt. Es ist egal, wenn es dann rechts aus dem Bild verschwindet.

*Mouse Deco*

Ersetze den Mauszeiger durch einen roten Punkt, während dieser sich über die Zeichenfläche bewegt.

Tip: `noCursor`

****

== Ereignisse
Sobald ein Programm, während dem es läuft, auf äussere Einflüsse reagieren muss, kommen Ereignisse (engl. `Events`) ins Spiel. Beispiele für Ereignisse:

- Linke Maustaste geklickt
- Enter Taste gedrückt
- Fenstergrösse hat geändert
- Systemzeit hat geändert

Eine Applikation, ein Programm, welches von einem Anwender bedient wird, muss zwangsläufig mit dem Anwender interagieren, um zum Beispiel auf Mausklicks reagieren zu können.

Im Folgenden ein Beispiel in P5.js:

+++
<iframe src="p5-sketches/index.html?s=events-demo" style="border:0; height: 100px;"></iframe>
+++

Bei jedem Click wird die Hintergrundfarbe geändert. Sowie die angezeigte Anzahl Clicks um eins erhöht.

Damit wir in JavaScript auf Ereignisse reagieren können, brauchen wir einen `EventHandler`, das ist eine Funktion, welche vom Computer automatisch aufgerufen wird, sobald das entsprechende Ereignis auftritt.

== P5.js – Interaktiv
In P5.js ist es möglich auf Events zu reagieren. Dies geschieht wiederum über Funktionen, welche einer Namenskonvention folgen.

Um auf einen Mausklick zu reagieren, wird eine Funktion mit dem Namen `mouseClicked` verwendet. Ist diese im Programmcode vorhanden, wird diese automatisch von P5.js aufgerufen, sobald der User mit der Maus auf die Zeichenfläche klickt. Diese Funktion ist also der `EventHandler` des Click Events.


+++
<script type="text/p5" src="p5-sketches/events-demo-simple.js" data-height="200">
</script>
+++


== Verzweigungen – bedingte Ausführung

Ein Weiterer wichtiger Baustein von Programmen sind Verzweigungen. Damit ist es möglich gewisse Anweisungen nur bedingt auszuführen.

Denken wir an ein Ballon-Treff-Spiel: Ein Kreis ändert ständig seine Position. Der Spieler bekommt einen Punkt, wenn er mit der Maus in den Kreis klickt. Klickt er ausserhalb des Ballons, gibt es keine Punkte. Die Anweisung "Erhöhe Punktezahl um eins" wird also bedingt ausgeführt. Die Bedingung ist "Click erfolgte auf Ballon".

In <<Pseudo-Code>> könnte man das so formulieren:

[source,javascript,linenums]
----
Wenn "Click erfolgte auf Ballon":
    "Erhöhe Punktezahl um eins"
Sonst:
    "Tue nichts"
----

Die Anweisung auf Zeile 2 wird nur ausgeführt, wenn die Bedingung auf Zeile 1 wahr (true) ist.
Ist die Bedingung auf Zeile 1 nicht wahr (false), dann wird nur die Anweisung auf Zeile 4 ausgeführt.

Die allgemein gültige <<Syntax>>, um eine solche Bedingung in JavaScript zu formulieren ist wie folgt:

[source,javascript,linenums]
----
if (<<Bedingung>>) {
    <<Anweisungen>>
} else {
    <<Anweisungen>>
}
----


TIP: Dieses Beispiel verwendet Platzhalter (mit << und >> gekennzeichnet). Es ist also nicht lauffähig, sondern illustriert die allgemein gültige Syntax in JavaScript.

Erläuterung:

Zeile 1:: Das Keyword um eine bedingte Ausführung einzuleiten ist `if` (engl. falls) {nbsp} +
Zeile 1:: Die runden Klammern (engl. Parentheses) sind zwingend nötig. Sie umfassen die ganze Bedingung. Eine Bedingung kann z.B. ein Vergleich `(a < 2)` sein. Eine Bedingung ist immer entweder true (wahr, zutreffend) oder false (nicht wahr, falsch). {nbsp} +
Zeile 1:: Die geschweifte Klammer (engl. Brace) eröffnet einen `Block`. Der Block reicht bis zu der ersten schliessenden geschweiften Klammer auf Zeile 3. Alle Anweisungen die sich innerhalb dieser beiden Klammern befinden, werden nur dann ausgeführt, wenn die Bedingung wahr ist. {nbsp} +
Zeile 2:: Eine oder mehrere Anweisungen, die bedingt ausgeführt werden.
Zeile 3:: Schliesst den Block, welcher auf Zeile 1 geöffnet wurde. Eröffnet einen neuen Block, welcher nur dann ausgeführt wird, wenn die Bedingung nicht wahr ist. Zwischen den beiden Blöcken muss das Keyword `else` (engl. sonst) stehen. {nbsp} +

Hier nun ein lauffähiges Beispiel:

[source,javascript,linenums]
----
let a = 2
if (a < 0) {
    a = 0
} else {
    a = a * 2
}
----


Eine bedingte Ausführung kann auch ohne else-Verzweigung definiert werden:

[source,javascript,linenums]
----
let a = 2
if (a < 0) {
    a = 0
}
----

Im Weiteren spielt es keine Rolle wieviel Leerzeichen oder Zeilenumbrüche verwendet werden. Wichtig sind die Steuerzeichen (z.B. Klammerpaare) und Keywords. Folgender Code ist also äquivalent, allerdings schlechter lesbar:

[source,javascript,linenums]
----
let a=2
if(a <0)            {  a = 0


}
----


=== Übung – Bedingte Ausführung
Du kannst diese Übungen direkt im obigen Editor lösen.

****
*Floating Rect*

Zeichne ein Rechteck, welches sich automatisch von ganz Links nach ganz Rechts bewegt …

. Sobald es den rechten Rand berührt, stoppt es.

. Sobald es den rechten Rand berührt, prallt es ab und bewegt sich nach links. Sobald es den linken Rand berührt, prallt es wieder ab und geht nach rechts. Bis es da wieder abprallt …

*Catch me*

. Zeichne einen Kreis. Wenn der Spieler daneben klickt, bekommt er einen Punkt abzug. Weniger als 0 Punkte geht nicht. {nbsp} +
Wenn der Spieler auf den Kreis klickt:
    .. bekommt er einen Punkt
    .. ändert der Kreis seine Position auf eine zufällige, neue Position

. Der Kreis ändert (zusätzlich) alle par Sekunden automatisch seine Position

. Die Grösse des Kreises ändert bei jedem Treffer.

Hinweis: `dist`, `random`, `frameRate`

****


=== Lernkontrolle
Ich weiss, ...
====
* [*] wie ich Programmteile nur bedingt ausführe
* [*] was die Keywords if, else und else if bedeuten
====

== Blöcke & Geltungsbereiche

Im Zusammenhang mit Verzweigungen haben wir das erste mal Blöcke verwendet. Ein Block besteht aus einer Liste von Anweisungen, welche von geschweiften Klammern (engl. Brace) umschlossen sind.

Theoretisch ist es also möglich einen Block zu definieren, auch ohne das man eine Verzweigung verwendet. Das sieht dann so aus:
[source,javascript,linenums]
----
let a = 0
{
    let b = 0
}
let c = 0
----

Im obigen Beispiel beginnt der explizit definierte Block auf Zeile 2 und geht bis Zeile 4. In JavaScript existiert immer auch ein impliziter Block: der, welcher das ganze Programm beinhaltet.

Ein Block kann einen anderen Block beinhalten. Man spricht dann von Verschachtelung:

[source,javascript,linenums]
----
let a = 0
{
    let b = 0
    {
        let b1 = 0
    }
}
let c = 0
----

Im obigen Beispiel beginnt auf Zeile 4 der verschachtelte Block und geht bis Zeile 6.

In der Praxis werden Blöcke selten allein verwendet, sondern zum Beispiel in Kombination mit Verzweigungen. Eine einfache Verzweigung kennen wir bereits. Hier nun ein Beispiel einer verschachtelten Verzweigung:

[source,javascript,linenums]
----
let a = 0
if (a > 0) {
    if (a <= 10) {
        // a >= 1 und <= 10
    } else {
        // a > 10
    }
} else {
    // a <= 0
}
----

=== Formatierung

Im Zusammenhang mit Blöcken wird gut sichtbar, wie hilfreich gut formatierter Code für uns Menschen ist. Es ist wie bei Texten in Büchern oder Zeitungen auch: Ein geordnetes Gesamtbild mit genügend Leerräumen (engl. whitespace) erhöht die Lesbarkeit und erfordert weniger Aufwand, um den Text zu verstehen.

Gut formatiert heisst:

* Pro Verschachtelungs-Stufe wird der gesamte Blockinhalt nach rechts eingerückt
* Abstände zwischen Steuerzeichen und Variablen ist einheitlich
* Zeilenumbrüche zwischen Steuerzeichen einheitlich

Das obige Beispiel ohne einheitliche Einrückung:

[source,javascript,linenums]
----
let a = 0
if (a > 0) {
if (a <= 10) {
  // a >= 1 und <= 10
    } else {
// a > 10
        }
} else {
        // a <= 0
    }
----

Das obige Beispiel ohne einheitliche Zeilenumbrüche und ohne einheitliche Abstände:

[source,javascript,linenums]
----
let a = 0
if ( a >0 )
{
    if ( a<=10) {
        // a >= 1 und <= 10
    }
    else {
        // a > 10
    }
}else{
    // a <= 0
}
----

TIP: Eine wichtige Funktion von IDEs ist die automatische Code-formatierung. Direkt bei der Eingabe, oder via Tastenkombination / Menüpunkt kann die ganze Datei automatisch korrekt formatiert werden.


=== Geltungsbereich

WARNING: In diesem Kapitel behandeln wir nicht alle Aspekte von Geltungsbereichen, sondern nur das minimal nötige für diesen Einführungskurs. Gewisse Definitionen / Erläuterungen sind daher nicht vollständig korrekt.

Blöcke dienen nicht nur der Formatierung und Gruppierung von Anweisungen. Blöcke definieren ebenfalls einen Geltungsbereich (engl. scope) für Variablen. Der Geltungsbereich einer Variable ist eine Reihe von Zeilen, in denen auf die Variabel zugegriffen (referenziert) werden kann. Der Gültigkeitsbereich einer Variabel startet auf der Zeile, auf der diese definiert wird, und geht bis an das Blockende.

Erinnern wir uns an das Beispiel von oben:

[source,javascript,linenums]
----
let a = 0
{
    let b = 0
}
let c = 0
----

* Der Geltungsbereich von `a` geht von Zeile 1 bis und mit 5.
* Der Geltungsbereich von `b` geht von Zeile 3 bis und mit 3.
* Der Geltungsbereich von `c` geht von Zeile 5 bis und mit 5.

Das impliziert:

* Geltungsbereiche beinhalten verschachtelte Blöcke
* Variabeln, welche in verschachtelten Blöcken definiert werden, sind in äusseren Blöcken nicht referenzierbar

Diese Tatsachen mit Kommentaren in einem Codebeispiel erläutert:

[source,javascript,linenums]
----
// Zugriff auf a nicht erlaubt, da noch nicht definiert
let a = 0
{
    // Zugriff auf a erlaubt, da im äusseren Block definiert
    let b = 0
}
// Zugriff auf b nicht erlaubt, da im inneren Block definiert
// Zugriff auf a erlaubt, da im gleichen Block, davor definiert
let c = 0
----

=== Lernkontrolle
====
* [*] Anhand eines Codebeispiels, kann ich den Geltungsbereich einer Variable bestimmen
* [*] Ich kenne die Kriterien korrekter Formatierung und kann diese Anwenden
====

== Schleifen

Eine weiterer wichtiger Baustein von Programmiersprachen sind Schleifen. Damit kann man eine Liste von Befehlen wiederholt ausführen. Es gibt verschiedene Schleifentypen. Die einfachste davon ist die `while`-Schleife.

Eine `while`-Schleife besteht lediglich aus einer Abbruchbedingung.

[source,javascript,linenums]
----
const stop = 100
let counter = 0
while(counter < stop) {
    text("Counter: " + counter, 10, 10)
    count = counter + 1
}
----

Im Beispiel oben, wird die Funktion `text` 100 mal ausgeführt. Begonnen wird mit `counter = 0`. Der letzte Durchgang wird mit `counter = 99` ausgeführt.

TIP: Es gibt weitere Schleifentypen (`for`, `do while`). Für die allermeisten Aufgaben reicht eine simple `while` Schleife jedoch bestens. Später, im Zusammenhang mit Arrays, lernst du den Schleifentypen `for of` kennen.

=== Übung – Schleifen

****
*...*

...

****

=== Datentypen II – Arrays

Generieren von Kreisen

== Funktionen – Definieren

== Datentypen III – Objekte


== Weiterführende JavaScript Ressourcen
* http://www.p5js.gym-wst.de/de/javascript
* https://nycdoe-cs4all.github.io/units/1/overview
* https://eloquentjavascript.net/
* https://developer.mozilla.org/de/docs/Web/JavaScript


[glossary]
== Glossar
[[Syntax]]Syntax:: Vorgabe innerhalb der Programmiersprache, wie man bestimmte Dinge zu schreiben hat. Die Syntax bestimmt an welchem Ort welches Zeichen gültig ist. Also z.B. ob ein Steuerzeichen (z.B. `{` oder `=`) erwartet wird, oder ein Keyword.
[[Pseudo-Code]]Pseudo-Code:: Mit Pseudo-Code kann man Prorgrammcode vereinfacht schreiben, so, dass der Sinn und Zweck des Algorithmus einfach notiert werden kann. Pseudo-Code ist unabhängig von den syntaktischen Details einer Programmiersprache und in der Regel nicht mit einem Computer ausführbar.
[[keyword]]Keyword:: Schlüsselwort. Ein reserviertes Wort, welches nicht für Bezeichner (z.B. von Variablen) verwendet werden kann. https://www.w3schools.com/js/js_reserved.asp[Liste aller JavaScript Keywords]
[[Pixel]]Pixel:: Ein Pixel ist ein Bildpunkt. Ein Computerbildschirm besteht aus tausenden von Pixel. Jeder Pixel kann eine Farbe annehmen. Bei älteren Bildschirmen kann man ein einzelnes Pixel mit blossem Auge erkennen (z.B. bei Röhrenbildschirmen die RGB-Dioden). Je mehr Pixel pro Zentimeter platziert sind, desto schärfer wirkt das Bild.
